### ISSUE TITLE
Using Your Information in a Guide I'm Making

### ISSUE THREAD

**Issue by matthewp0** [StuckInLimbo/OBS-ReplayBuffer-Setup#2]
I'm currently making a guide to use OBS as an alternative to NVIDIA Shadowplay, so it heavily uses the information in this Setup in my guide.  But you've been away so I'm letting you know that I will provide a link to the document once I finish, I've added a credits page as well as providing a link to this page where I use the information.  I want you to let me know whenever you come back if you want to discuss a compromise or if it's fine the way it is.

**Comment by matthewp0** [comment]
https://github.com/MFGAVIN/OBS-Alternative-to-Shadowplay/blob/main/README.md

**Comment by StuckInLimbo** [comment]
After reviewing your repo, I saw that I was credited and I am fine with my information being used as I posted it publicly for this explicit reason. Sorry for getting back to you so late, I had kind of forgotten I had made this document as I made it for my friends who used shadowplay.
